version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run:
          name: Run gofmt
          command: diff -u <(echo -n) <(gofmt -d -s ./)

      - run:
          name: Run tests
          command: go test -v ./...

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build:
    jobs:
      - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          requires:
            - build
